name: Validate Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./setup.yml
      - name: Lint
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./setup.yml
      - name: Build
        run: npm run build
