name: Validate Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build
